# Generated by Django 3.1.12 on 2025-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0002_alter_compound_id_alter_modeltraining_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modeltraining',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
